### ISSUE TITLE
torch-compiled runtime implementation results in confusing status stats

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#82]
The `turnkey benchmark INPUT_FILES --runtime torch-compiled` option performs a torch.compile(model) and then benchmarks the result.

The `torch.compile(model)` call is inside the `TorchRT(BaseRT)` class, meaning that it technically takes place during benchmarking. This means we don't get any telemetry in the stats/report about whether the "build" (compile) failed or not.

It ends up looking like this on compilation failure, which is confusing:

```
evaluations:
  x86_torch-compiled:
    benchmark_status: incomplete
    build_status: error
    device_type: x86
    iterations: 100
    runtime: torch-compiled
```

It should be:

```
evaluations:
  x86_torch-compiled:
    benchmark_status: not_started
    build_status: error
    device_type: x86
    iterations: 100
    runtime: torch-compiled
```

Bad solution: set the stats in `TorchRT` such that build and benchmark status are correctly captured.

Better solution: perform the `torch.compile()` in a proper build sequence

cc @danielholanda @ramkrishna2910
